<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.deepoove</groupId>
	<artifactId>poi-tl-parent</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>

	<name>poi-tl-parent</name>
	<description>A better way to generate word(docx) with template, based on Apache POI</description>
	<url>https://deepoove.com/poi-tl</url>

	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>Sayi</name>
			<email>[EMAIL_REDACTED]</email>
			<url>https://github.com/Sayi</url>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:[EMAIL_REDACTED]:Sayi/poi-tl.git</connection>
		<developerConnection>scm:git:[EMAIL_REDACTED]:Sayi/poi-tl.git</developerConnection>
		<url>[EMAIL_REDACTED]:Sayi/poi-tl.git</url>
	</scm>

	<modules>
		<module>poi-tl</module>
		<module>plugin/poi-tl-plugin-highlight</module>
		<module>plugin/poi-tl-plugin-markdown</module>
		<module>plugin/poi-tl-plugin-barcode</module>
		<module>support/poi-tl-jsonmodel-support</module>
		<module>support/poi-tl-cli</module>
	</modules>

	<properties>
		<revision>1.13.0-SNAPSHOT</revision>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.test.failure.ignore>true</maven.test.failure.ignore>

		<!-- Dependency Versions -->
		<poi.version>5.4.0</poi.version>
		<slf4j.version>1.7.32</slf4j.version>
		<commons-lang3.version>3.18.0</commons-lang3.version>
		<batik.version>1.17</batik.version>
		<spring-expression.version>6.0.8</spring-expression.version>
		<junit-jupiter.version>5.6.0</junit-jupiter.version>
		<logback.version>1.2.13</logback.version>
		<swagger-parser.version>1.0.50</swagger-parser.version>
		<gson.version>2.9.0</gson.version>
		<gson-extras.version>0.4.0</gson-extras.version>
		<typetools.version>0.6.3</typetools.version>
		<slf4j-simple.version>1.7.7</slf4j-simple.version>
		<codehighlight.version>1.0.3</codehighlight.version>
		<commonmark.version>0.17.1</commonmark.version>
		<zxing.version>3.5.2</zxing.version>
		<jcommander.version>1.82</jcommander.version>
		<log4j-slf4j-impl.version>2.17.2</log4j-slf4j-impl.version>

		<!-- Plugin Versions -->
		<maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
		<maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version>
		<maven-failsafe-plugin.version>2.22.2</maven-failsafe-plugin.version>
		<maven-source-plugin.version>3.3.0</maven-source-plugin.version>
		<maven-javadoc-plugin.version>3.6.3</maven-javadoc-plugin.version>
		<maven-gpg-plugin.version>3.2.4</maven-gpg-plugin.version>
		<flatten-maven-plugin.version>1.6.0</flatten-maven-plugin.version>
		<maven-assembly-plugin.version>3.1.0</maven-assembly-plugin.version>
		<cobertura-maven-plugin.version>2.7</cobertura-maven-plugin.version>
		<coveralls-maven-plugin.version>4.3.0</coveralls-maven-plugin.version>
	</properties>

	<distributionManagement>
		<snapshotRepository>
			<id>oss</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		</snapshotRepository>
		<repository>
			<id>oss</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
	</distributionManagement>

	<dependencyManagement>
		<dependencies>
			<!-- Reactor Modules -->
			<dependency>
				<groupId>com.deepoove</groupId>
				<artifactId>poi-tl</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.deepoove</groupId>
				<artifactId>poi-tl-plugin-highlight</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.deepoove</groupId>
				<artifactId>poi-tl-plugin-markdown</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.deepoove</groupId>
				<artifactId>poi-tl-plugin-barcode</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.deepoove</groupId>
				<artifactId>poi-tl-jsonmodel-support</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.deepoove</groupId>
				<artifactId>poi-tl-cli</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- Third-party Dependencies -->
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>${slf4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${commons-lang3.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi-ooxml</artifactId>
				<version>${poi.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.xmlgraphics</groupId>
				<artifactId>batik-transcoder</artifactId>
				<version>${batik.version}</version>
				<exclusions>
					<exclusion>
						<groupId>xalan</groupId>
						<artifactId>xalan</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.apache.xmlgraphics</groupId>
				<artifactId>batik-codec</artifactId>
				<version>${batik.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-expression</artifactId>
				<version>${spring-expression.version}</version>
			</dependency>
			<dependency>
				<groupId>ch.qos.logback</groupId>
				<artifactId>logback-core</artifactId>
				<version>${logback.version}</version>
			</dependency>
			<dependency>
				<groupId>ch.qos.logback</groupId>
				<artifactId>logback-classic</artifactId>
				<version>${logback.version}</version>
			</dependency>
			<dependency>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-parser</artifactId>
				<version>${swagger-parser.version}</version>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-api</artifactId>
				<version>${junit-jupiter.version}</version>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-engine</artifactId>
				<version>${junit-jupiter.version}</version>
			</dependency>
			<dependency>
				<groupId>com.google.code.gson</groupId>
				<artifactId>gson</artifactId>
				<version>${gson.version}</version>
			</dependency>
			<dependency>
				<groupId>org.danilopianini</groupId>
				<artifactId>gson-extras</artifactId>
				<version>${gson-extras.version}</version>
			</dependency>
			<dependency>
				<groupId>net.jodah</groupId>
				<artifactId>typetools</artifactId>
				<version>${typetools.version}</version>
			</dependency>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-simple</artifactId>
				<version>${slf4j-simple.version}</version>
			</dependency>
			<dependency>
				<groupId>com.deepoove</groupId>
				<artifactId>codehighlight</artifactId>
				<version>${codehighlight.version}</version>
			</dependency>
			<dependency>
				<groupId>com.google.zxing</groupId>
				<artifactId>core</artifactId>
				<version>${zxing.version}</version>
			</dependency>
			<dependency>
				<groupId>org.commonmark</groupId>
				<artifactId>commonmark</artifactId>
				<version>${commonmark.version}</version>
			</dependency>
			<dependency>
				<groupId>org.commonmark</groupId>
				<artifactId>commonmark-ext-gfm-tables</artifactId>
				<version>${commonmark.version}</version>
			</dependency>
			<dependency>
				<groupId>com.beust</groupId>
				<artifactId>jcommander</artifactId>
				<version>${jcommander.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-slf4j-impl</artifactId>
				<version>${log4j-slf4j-impl.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-plugin.version}</version>
					<configuration>
						<source>${maven.compiler.source}</source>
						<target>${maven.compiler.target}</target>
						<encoding>${project.build.sourceEncoding}</encoding>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${maven-surefire-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>${maven-failsafe-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>flatten-maven-plugin</artifactId>
					<version>${flatten-maven-plugin.version}</version>
					<configuration>
						<updatePomFile>true</updatePomFile>
						<flattenMode>resolveCiFriendliesOnly</flattenMode>
					</configuration>
					<executions>
						<execution>
							<id>flatten</id>
							<phase>process-resources</phase>
							<goals>
								<goal>flatten</goal>
							</goals>
						</execution>
						<execution>
							<id>flatten.clean</id>
							<phase>clean</phase>
							<goals>
								<goal>clean</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>${maven-source-plugin.version}</version>
					<executions>
						<execution>
							<id>attach-sources</id>
							<phase>package</phase>
							<goals>
								<goal>jar-no-fork</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>${maven-javadoc-plugin.version}</version>
					<configuration>
						<quiet>true</quiet>
						<nonavbar>true</nonavbar>
						<notree>true</notree>
						<nocomment>true</nocomment>
						<nohelp>true</nohelp>
						<doclint>none</doclint>
					</configuration>
					<executions>
						<execution>
							<id>attach-javadocs</id>
							<goals>
								<goal>jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-gpg-plugin</artifactId>
					<version>${maven-gpg-plugin.version}</version>
					<executions>
						<execution>
							<id>sign-artifacts</id>
							<phase>verify</phase>
							<goals>
								<goal>sign</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-assembly-plugin</artifactId>
					<version>${maven-assembly-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>cobertura-maven-plugin</artifactId>
					<version>${cobertura-maven-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.eluder.coveralls</groupId>
					<artifactId>coveralls-maven-plugin</artifactId>
					<version>${coveralls-maven-plugin.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>release</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
