/*
 * Copyright 2014-2026 Sayi
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.deepoove.poi.plugin.barcode;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;

import javax.imageio.ImageIO;

import org.junit.jupiter.api.Assertions;

import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Result;
import com.google.zxing.RGBLuminanceSource;
import com.google.zxing.common.HybridBinarizer;

/**
 * Round trip helper: generate an image out of the plugin, then decode it with
 * ZXing to prove the symbol is really scannable. Only classes of zxing core are
 * used, the plugin does not depend on zxing javase.
 *
 * @author Sayi
 */
final class BarcodeDecodeSupport {

    private BarcodeDecodeSupport() {
    }

    static BufferedImage toImage(byte[] png) throws IOException {
        Assertions.assertNotNull(png, "generated bytes must not be null");
        Assertions.assertTrue(png.length > 0, "generated bytes must not be empty");
        BufferedImage image = ImageIO.read(new ByteArrayInputStream(png));
        Assertions.assertNotNull(image, "generated bytes must be a readable image");
        return image;
    }

    static Result decode(byte[] png) throws Exception {
        return decode(toImage(png));
    }

    static Result decode(BufferedImage image) throws Exception {
        int width = image.getWidth();
        int height = image.getHeight();
        int[] pixels = image.getRGB(0, 0, width, height, null, 0, width);
        LuminanceSource source = new RGBLuminanceSource(width, height, pixels);
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
        return new MultiFormatReader().decode(bitmap);
    }

    /**
     * Number of pixels equal to the given rgb value.
     */
    static int countColor(BufferedImage image, int rgb) {
        int count = 0;
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                if (image.getRGB(x, y) == rgb) {
                    count++;
                }
            }
        }
        return count;
    }

    static boolean samePixels(byte[] pngA, byte[] pngB) throws IOException {
        BufferedImage a = toImage(pngA);
        BufferedImage b = toImage(pngB);
        if (a.getWidth() != b.getWidth() || a.getHeight() != b.getHeight()) {
            return false;
        }
        for (int y = 0; y < a.getHeight(); y++) {
            for (int x = 0; x < a.getWidth(); x++) {
                if (a.getRGB(x, y) != b.getRGB(x, y)) {
                    return false;
                }
            }
        }
        return true;
    }

    static boolean isBorderClean(BufferedImage image, int backgroundRgb) {
        int width = image.getWidth();
        int height = image.getHeight();
        for (int x = 0; x < width; x++) {
            if (image.getRGB(x, 0) != backgroundRgb || image.getRGB(x, height - 1) != backgroundRgb) {
                return false;
            }
        }
        for (int y = 0; y < height; y++) {
            if (image.getRGB(0, y) != backgroundRgb || image.getRGB(width - 1, y) != backgroundRgb) {
                return false;
            }
        }
        return true;
    }

}
